blank_issues_enabled: false
contact_links:
  - name: Discussion
    url: https://github.com/Alireza29675/desk/discussions
    about: Questions, ideas, or anything that isn't quite a bug or feature request.
